title: My Project Documentation
description: Documentation for my project using Jekyll
theme: minima
baseurl: "/api" # Eğer alt dizin kullanıyorsanız buraya alt dizin adını yazın


navbar: 
  - title: "Home"
    url: "/"
  - title: "Api Documantation
    url: "/api/"
  - title: "Activation"
    url: "/api/activation"
  - title: "Analysis"
    url: "/api/Analysis"
  
